DROP DATABASE IF EXISTS `api`;
CREATE DATABASE `api` CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON `api`.* TO 'api'@'%' IDENTIFIED BY 'api012' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `api`.* TO 'api'@'localhost' IDENTIFIED BY 'api012' WITH GRANT OPTION;

DROP DATABASE IF EXISTS `api_test`;
CREATE DATABASE `api_test` CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON `api_test`.* TO 'api'@'%' IDENTIFIED BY 'api012' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `api_test`.* TO 'api'@'localhost' IDENTIFIED BY 'api012' WITH GRANT OPTION;
